export default {
  FETCH_LIST_REQUEST: 'AUTHOR_FETCH_LIST_REQUEST',
  FETCH_LIST_SUCCESS: 'AUTHOR_FETCH_LIST_SUCCESS',
  FETCH_LIST_FAILURE: 'AUTHOR_FETCH_LIST_FAILURE',
  EDITING_ITEM_CHANGE: 'AUTHOR_EDITING_ITEM_CHANGE',
  EDITING_ITEM_CANCEL: 'AUTHOR_EDITING_ITEM_CANCEL',
  EDITING_ITEM_SAVE_REQUEST: 'AUTHOR_EDITING_ITEM_SAVE_REQUEST',
  EDITING_ITEM_SAVE_SUCCESS: 'AUTHOR_EDITING_ITEM_SAVE_SUCCESS',
  EDITING_ITEM_SAVE_FAILURE: 'AUTHOR_EDITING_ITEM_SAVE_FAILURE',
  EDITING_ITEM_DELETE_REQUEST: 'AUTHOR_EDITING_ITEM_DELETE_REQUEST',
  EDITING_ITEM_DELETE_SUCCESS: 'AUTHOR_EDITING_ITEM_DELETE_SUCCESS',
  EDITING_ITEM_DELETE_FAILURE: 'AUTHOR_EDITING_ITEM_DELETE_FAILURE',
  CURRENT_ITEM_SELECT: 'AUTHOR_CURRENT_ITEM_SELECT',
};
